name: Build CmdHckSqli APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          libncurses6 libncurses-dev \  # Updated package names
          libtinfo6 cmake \             # Updated package names
          zlib1g-dev

    - name: Install Buildozer
      run: pip install buildozer cython

    - name: Configure Android SDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools ~/android-sdk
        export ANDROID_SDK_ROOT=~/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"

    - name: Build APK
      run: |
        buildozer -v android debug
