name: Build CmdHckSqli APK

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk
        pip install buildozer cython
        
    - name: Build APK
      run: |
        buildozer init
        echo "[app]
        title = CmdHckSqli
        package.name = cmdhcksqli
        requirements = python3,kivy==2.2.1,kivymd==1.1.1
        android.permissions = INTERNET" > buildozer.spec
        buildozer -v android debug
