name: Build CmdHckSqli APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          build-essential \
          zlib1g-dev \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer
      run: pip install buildozer cython

    - name: Setup Android environment
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Download Android Command Line Tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -qq commandlinetools-linux-9477386_latest.zip -d cmdline-tools
        mkdir -p ~/android-sdk/cmdline-tools
        mv cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
        
        # Setup environment variables
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_PATH
        
        # Accept licenses and install components
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0"

    - name: Build APK
      run: |
        # Generate buildozer.spec
        cat > buildozer.spec <<EOL
        [app]
        title = CmdHckSqli
        package.name = cmdhcksqli
        requirements = python3,kivy==2.2.1,kivymd==1.1.1
        android.api = 33
        android.minapi = 21
        android.sdk_path = $HOME/android-sdk
        android.ndk_path = $HOME/android-ndk
        android.accept_sdk_license = True
        EOL
        
        # Run build
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: CmdHckSqli-APK
        path: bin/*.apk
