name: Build CmdHckSqli APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          build-essential zlib1g-dev \
          libncurses5-dev libffi-dev \
          libssl-dev python3-pip

    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: |
          ~/.android
          ~/android-sdk
        key: ${{ runner.os }}-android-${{ hashFiles('buildozer.spec') }}

    - name: Set up Android SDK
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Download latest command line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -qq cmdline-tools.zip -d cmdline-tools
        mkdir -p ~/android-sdk/cmdline-tools
        mv cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
        
        # Set environment variables
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_PATH
        
        # Accept licenses and install components
        yes | sdkmanager --licenses > /dev/null
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;34.0.0" "ndk;25.2.9519653"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build APK
      run: |
        # Create buildozer.spec if missing
        if [ ! -f buildozer.spec ]; then
          buildozer init
          sed -i 's/^requirements =.*/requirements = python3,kivy==2.2.1,kivymd==1.1.1,requests,pygments/' buildozer.spec
          echo "android.api = 33" >> buildozer.spec
          echo "android.minapi = 21" >> buildozer.spec
          echo "android.sdk_path = $HOME/android-sdk" >> buildozer.spec
          echo "android.ndk_path = $HOME/android-sdk/ndk/25.2.9519653" >> buildozer.spec
        fi
        
        buildozer -v android release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: CmdHckSqli-APK
        path: bin/*.apk
        retention-days: 7

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Build-Logs
        path: |
          .buildozer/**/*.log
          buildozer.spec
